### ISSUE TITLE
check typos in Data_Rhythm_Final_English.csv

### ISSUE THREAD

**Issue by chiarabarbieri** [chundrac/phylo-acoustic-rhythm#1]
1) correct typos in latin names of species.
*Chlorocebus pygerythus* --> *Chlorocebus pygerythrus*
*Ophisthocomus hoazin* --> *Opisthocomus hoazin*
*Zaedyus pichyi* --> *Zaedyus pichiy*

2) replace the column Scientific_Name_(Replacement_Species) with the one in attachment, which corresponds to the same column name in the genetic info file 
[Scientific_Name_(Replacement_Species).csv](https://github.com/user-attachments/files/15919961/Scientific_Name_.Replacement_Species.csv)

**Comment by chundrac** [comment]
This should be taken care of in the inference scripts, e.g., https://github.com/chundrac/phylo-acoustic-rhythm/blob/8da3828d969cdcebb29c1f8d8a9775bf7590a99d/OU_models/run_model.R#L26

**Comment by chundrac** [comment]
This should be taken care of in the inference scripts, e.g., https://github.com/chundrac/phylo-acoustic-rhythm/blob/8da3828d969cdcebb29c1f8d8a9775bf7590a99d/OU_models/run_model.R#L26
